-   name: Install python setup tools
    yum: name=python-setuptools
    tags: docker

-   name: Install Pypi
    easy_install: name=pip
    tags: docker

-   name: Install docker-py
    pip: name=docker-py version=1.2.3
    tags: docker

-   name: Install Docker
    yum: name=docker state=latest
    tags: docker

-   name: Configure docker
    copy: src=sysconfig-docker dest=/etc/sysconfig/docker
    notify: restart docker

-   name: Make sure Docker is running
    service: name=docker state=running
    tags: docker

-   name: Make sure Docker boots on startup
    service: name=docker enabled=yes
