common: &common
  loglevel: debug
  standalone: true
  search_backend: "_env:SEARCH_BACKEND:"
  sqlalchemy_index_database: "_env:SQLALCHEMY_INDEX_DATABASE:sqlite:////tmp/docker-registry.db"

  secret_key: @@SEC_KEY@@

file: &file
  <<: *common
  storage: local
  storage_path: /docker-registry-storage
