jenkins-nginx:
    build: jenkins-nginx
    container_name: jenkins-nginx
    ports:
      - "443:443"
    volumes:
      - "/Users/denschu/git/continuous-delivery-infrastructure/testserver/certs:/etc/nginx/ssl"
    links:
      - jenkins-master
jenkins-master:
  build: jenkins-master
  container_name: jenkins-master
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  volumes:
    - $HOME/jenkins_home:/var/jenkins_home
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/usr/local/bin/docker:/bin/docker"
  extra_hosts:
    # Private Docker Registry
    - "docker.denschu.de:192.168.50.96"
    # Example Host for the Example Application
    - "testserver.denschu.de:192.168.50.97"
  user: root
