- name: Latest container is pulled
  shell: sudo docker pull jboss/wildfly

- name: Container is absent
  docker:
    image=jboss/wildfly
    name=example
    state=absent

- name: Container is running
  docker:
    name=example
    image=jboss/wildfly
    ports=8080:8080
    state=running
